name: Build and Deploy to Steam

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/
    
    - name: Setup Steam CLI
      run: |
        mkdir -p ~/steamcmd
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_osx.tar.gz" | tar zxvf - -C ~/steamcmd
    
    - name: Deploy to Steam
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        STEAM_GUARD_CODE: ${{ secrets.STEAM_GUARD_CODE }}
      run: |
        ~/steamcmd/steamcmd.sh +login $STEAM_USERNAME $STEAM_PASSWORD $STEAM_GUARD_CODE +run_app_build ../steam/app_build3.vdf +quit 